server:
  AppVersion: 1.0.0
  Port: :5000
  JwtSecretKey: Controcarro3
  CtxUserkey: User
  ReadTimeout: 10
  WriteTimeout: 10

postgres:
  PostgresqlHost: postgresqlmirror
  PostgresqlPort: 5432
  PostgresqlUser: minotauro
  PostgresqlPassword: Controcarro3
  PostgresqlDbname: quizapp

cors:
  AllowOrigins: [http://localhost:9090,http://localhost:3000]
  AllowMethods: [GET,DELETE,POST,PATCH,PUT]
  AllowHeaders: [Content-Type,Content-Length,Authorization]
  